#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Base_de_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbGolden")]
	public partial class Db_GoldDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTD_CuentaAhorros(TD_CuentaAhorros instance);
    partial void UpdateTD_CuentaAhorros(TD_CuentaAhorros instance);
    partial void DeleteTD_CuentaAhorros(TD_CuentaAhorros instance);
    partial void InsertTD_CuentaCorriente(TD_CuentaCorriente instance);
    partial void UpdateTD_CuentaCorriente(TD_CuentaCorriente instance);
    partial void DeleteTD_CuentaCorriente(TD_CuentaCorriente instance);
    partial void InsertTD_CuentaCredito(TD_CuentaCredito instance);
    partial void UpdateTD_CuentaCredito(TD_CuentaCredito instance);
    partial void DeleteTD_CuentaCredito(TD_CuentaCredito instance);
    partial void InsertTD_CuentaPrestamo(TD_CuentaPrestamo instance);
    partial void UpdateTD_CuentaPrestamo(TD_CuentaPrestamo instance);
    partial void DeleteTD_CuentaPrestamo(TD_CuentaPrestamo instance);
    partial void InsertTD_Transacciones(TD_Transacciones instance);
    partial void UpdateTD_Transacciones(TD_Transacciones instance);
    partial void DeleteTD_Transacciones(TD_Transacciones instance);
    partial void InsertTM_Clientes(TM_Clientes instance);
    partial void UpdateTM_Clientes(TM_Clientes instance);
    partial void DeleteTM_Clientes(TM_Clientes instance);
    partial void InsertTM_Prestamos(TM_Prestamos instance);
    partial void UpdateTM_Prestamos(TM_Prestamos instance);
    partial void DeleteTM_Prestamos(TM_Prestamos instance);
    partial void InsertTM_ServicioAhorros(TM_ServicioAhorros instance);
    partial void UpdateTM_ServicioAhorros(TM_ServicioAhorros instance);
    partial void DeleteTM_ServicioAhorros(TM_ServicioAhorros instance);
    partial void InsertTM_ServicioCorriente(TM_ServicioCorriente instance);
    partial void UpdateTM_ServicioCorriente(TM_ServicioCorriente instance);
    partial void DeleteTM_ServicioCorriente(TM_ServicioCorriente instance);
    partial void InsertTM_ServicioCredito(TM_ServicioCredito instance);
    partial void UpdateTM_ServicioCredito(TM_ServicioCredito instance);
    partial void DeleteTM_ServicioCredito(TM_ServicioCredito instance);
    #endregion
		
		public Db_GoldDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.DbGoldenConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Db_GoldDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_GoldDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_GoldDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_GoldDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TD_CuentaAhorros> TD_CuentaAhorros
		{
			get
			{
				return this.GetTable<TD_CuentaAhorros>();
			}
		}
		
		public System.Data.Linq.Table<TD_CuentaCorriente> TD_CuentaCorriente
		{
			get
			{
				return this.GetTable<TD_CuentaCorriente>();
			}
		}
		
		public System.Data.Linq.Table<TD_CuentaCredito> TD_CuentaCredito
		{
			get
			{
				return this.GetTable<TD_CuentaCredito>();
			}
		}
		
		public System.Data.Linq.Table<TD_CuentaPrestamo> TD_CuentaPrestamo
		{
			get
			{
				return this.GetTable<TD_CuentaPrestamo>();
			}
		}
		
		public System.Data.Linq.Table<TD_Transacciones> TD_Transacciones
		{
			get
			{
				return this.GetTable<TD_Transacciones>();
			}
		}
		
		public System.Data.Linq.Table<TM_Clientes> TM_Clientes
		{
			get
			{
				return this.GetTable<TM_Clientes>();
			}
		}
		
		public System.Data.Linq.Table<TM_Prestamos> TM_Prestamos
		{
			get
			{
				return this.GetTable<TM_Prestamos>();
			}
		}
		
		public System.Data.Linq.Table<TM_ServicioAhorros> TM_ServicioAhorros
		{
			get
			{
				return this.GetTable<TM_ServicioAhorros>();
			}
		}
		
		public System.Data.Linq.Table<TM_ServicioCorriente> TM_ServicioCorriente
		{
			get
			{
				return this.GetTable<TM_ServicioCorriente>();
			}
		}
		
		public System.Data.Linq.Table<TM_ServicioCredito> TM_ServicioCredito
		{
			get
			{
				return this.GetTable<TM_ServicioCredito>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_CuentaAhorros")]
	public partial class TD_CuentaAhorros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numerocuenta;
		
		private System.Nullable<int> _clienteid;
		
		private System.Nullable<int> _servicio_ahorros_id;
		
		private System.Nullable<float> _balance;
		
		private System.Nullable<float> _tasa_interes;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_ServicioAhorros> _TM_ServicioAhorros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumerocuentaChanging(int value);
    partial void OnnumerocuentaChanged();
    partial void OnclienteidChanging(System.Nullable<int> value);
    partial void OnclienteidChanged();
    partial void Onservicio_ahorros_idChanging(System.Nullable<int> value);
    partial void Onservicio_ahorros_idChanged();
    partial void OnbalanceChanging(System.Nullable<float> value);
    partial void OnbalanceChanged();
    partial void Ontasa_interesChanging(System.Nullable<float> value);
    partial void Ontasa_interesChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TD_CuentaAhorros()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			this._TM_ServicioAhorros = default(EntityRef<TM_ServicioAhorros>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocuenta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numerocuenta
		{
			get
			{
				return this._numerocuenta;
			}
			set
			{
				if ((this._numerocuenta != value))
				{
					this.OnnumerocuentaChanging(value);
					this.SendPropertyChanging();
					this._numerocuenta = value;
					this.SendPropertyChanged("numerocuenta");
					this.OnnumerocuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int")]
		public System.Nullable<int> clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_ahorros_id", DbType="Int")]
		public System.Nullable<int> servicio_ahorros_id
		{
			get
			{
				return this._servicio_ahorros_id;
			}
			set
			{
				if ((this._servicio_ahorros_id != value))
				{
					if (this._TM_ServicioAhorros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onservicio_ahorros_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_ahorros_id = value;
					this.SendPropertyChanged("servicio_ahorros_id");
					this.Onservicio_ahorros_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Real")]
		public System.Nullable<float> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_interes", DbType="Real")]
		public System.Nullable<float> tasa_interes
		{
			get
			{
				return this._tasa_interes;
			}
			set
			{
				if ((this._tasa_interes != value))
				{
					this.Ontasa_interesChanging(value);
					this.SendPropertyChanging();
					this._tasa_interes = value;
					this.SendPropertyChanged("tasa_interes");
					this.Ontasa_interesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaAhorros", Storage="_TM_Clientes", ThisKey="clienteid", OtherKey="clienteid", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TD_CuentaAhorros.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaAhorros.Add(this);
						this._clienteid = value.clienteid;
					}
					else
					{
						this._clienteid = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioAhorros_TD_CuentaAhorros", Storage="_TM_ServicioAhorros", ThisKey="servicio_ahorros_id", OtherKey="servicio_ahorros_id", IsForeignKey=true)]
		public TM_ServicioAhorros TM_ServicioAhorros
		{
			get
			{
				return this._TM_ServicioAhorros.Entity;
			}
			set
			{
				TM_ServicioAhorros previousValue = this._TM_ServicioAhorros.Entity;
				if (((previousValue != value) 
							|| (this._TM_ServicioAhorros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_ServicioAhorros.Entity = null;
						previousValue.TD_CuentaAhorros.Remove(this);
					}
					this._TM_ServicioAhorros.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaAhorros.Add(this);
						this._servicio_ahorros_id = value.servicio_ahorros_id;
					}
					else
					{
						this._servicio_ahorros_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_ServicioAhorros");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_CuentaCorriente")]
	public partial class TD_CuentaCorriente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numerocuenta;
		
		private System.Nullable<int> _clienteid;
		
		private System.Nullable<int> _servicio_corriente_id;
		
		private System.Nullable<float> _balance;
		
		private System.Nullable<float> _balance_sobregiro;
		
		private System.Nullable<float> _tasa_interes;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_ServicioCorriente> _TM_ServicioCorriente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumerocuentaChanging(int value);
    partial void OnnumerocuentaChanged();
    partial void OnclienteidChanging(System.Nullable<int> value);
    partial void OnclienteidChanged();
    partial void Onservicio_corriente_idChanging(System.Nullable<int> value);
    partial void Onservicio_corriente_idChanged();
    partial void OnbalanceChanging(System.Nullable<float> value);
    partial void OnbalanceChanged();
    partial void Onbalance_sobregiroChanging(System.Nullable<float> value);
    partial void Onbalance_sobregiroChanged();
    partial void Ontasa_interesChanging(System.Nullable<float> value);
    partial void Ontasa_interesChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TD_CuentaCorriente()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			this._TM_ServicioCorriente = default(EntityRef<TM_ServicioCorriente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocuenta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numerocuenta
		{
			get
			{
				return this._numerocuenta;
			}
			set
			{
				if ((this._numerocuenta != value))
				{
					this.OnnumerocuentaChanging(value);
					this.SendPropertyChanging();
					this._numerocuenta = value;
					this.SendPropertyChanged("numerocuenta");
					this.OnnumerocuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int")]
		public System.Nullable<int> clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_corriente_id", DbType="Int")]
		public System.Nullable<int> servicio_corriente_id
		{
			get
			{
				return this._servicio_corriente_id;
			}
			set
			{
				if ((this._servicio_corriente_id != value))
				{
					if (this._TM_ServicioCorriente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onservicio_corriente_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_corriente_id = value;
					this.SendPropertyChanged("servicio_corriente_id");
					this.Onservicio_corriente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Real")]
		public System.Nullable<float> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_sobregiro", DbType="Real")]
		public System.Nullable<float> balance_sobregiro
		{
			get
			{
				return this._balance_sobregiro;
			}
			set
			{
				if ((this._balance_sobregiro != value))
				{
					this.Onbalance_sobregiroChanging(value);
					this.SendPropertyChanging();
					this._balance_sobregiro = value;
					this.SendPropertyChanged("balance_sobregiro");
					this.Onbalance_sobregiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_interes", DbType="Real")]
		public System.Nullable<float> tasa_interes
		{
			get
			{
				return this._tasa_interes;
			}
			set
			{
				if ((this._tasa_interes != value))
				{
					this.Ontasa_interesChanging(value);
					this.SendPropertyChanging();
					this._tasa_interes = value;
					this.SendPropertyChanged("tasa_interes");
					this.Ontasa_interesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaCorriente", Storage="_TM_Clientes", ThisKey="clienteid", OtherKey="clienteid", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TD_CuentaCorriente.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaCorriente.Add(this);
						this._clienteid = value.clienteid;
					}
					else
					{
						this._clienteid = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioCorriente_TD_CuentaCorriente", Storage="_TM_ServicioCorriente", ThisKey="servicio_corriente_id", OtherKey="servicio_corriente_id", IsForeignKey=true)]
		public TM_ServicioCorriente TM_ServicioCorriente
		{
			get
			{
				return this._TM_ServicioCorriente.Entity;
			}
			set
			{
				TM_ServicioCorriente previousValue = this._TM_ServicioCorriente.Entity;
				if (((previousValue != value) 
							|| (this._TM_ServicioCorriente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_ServicioCorriente.Entity = null;
						previousValue.TD_CuentaCorriente.Remove(this);
					}
					this._TM_ServicioCorriente.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaCorriente.Add(this);
						this._servicio_corriente_id = value.servicio_corriente_id;
					}
					else
					{
						this._servicio_corriente_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_ServicioCorriente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_CuentaCredito")]
	public partial class TD_CuentaCredito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numerocuenta;
		
		private System.Nullable<int> _clienteid;
		
		private System.Nullable<int> _servicio_credito_id;
		
		private System.Nullable<float> _balance_corte;
		
		private System.Nullable<float> _balance_sobregiro;
		
		private string _fechacorte;
		
		private System.Nullable<float> _balance_fecha;
		
		private string _corte_total;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_ServicioCredito> _TM_ServicioCredito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumerocuentaChanging(int value);
    partial void OnnumerocuentaChanged();
    partial void OnclienteidChanging(System.Nullable<int> value);
    partial void OnclienteidChanged();
    partial void Onservicio_credito_idChanging(System.Nullable<int> value);
    partial void Onservicio_credito_idChanged();
    partial void Onbalance_corteChanging(System.Nullable<float> value);
    partial void Onbalance_corteChanged();
    partial void Onbalance_sobregiroChanging(System.Nullable<float> value);
    partial void Onbalance_sobregiroChanged();
    partial void OnfechacorteChanging(string value);
    partial void OnfechacorteChanged();
    partial void Onbalance_fechaChanging(System.Nullable<float> value);
    partial void Onbalance_fechaChanged();
    partial void Oncorte_totalChanging(string value);
    partial void Oncorte_totalChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TD_CuentaCredito()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			this._TM_ServicioCredito = default(EntityRef<TM_ServicioCredito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocuenta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numerocuenta
		{
			get
			{
				return this._numerocuenta;
			}
			set
			{
				if ((this._numerocuenta != value))
				{
					this.OnnumerocuentaChanging(value);
					this.SendPropertyChanging();
					this._numerocuenta = value;
					this.SendPropertyChanged("numerocuenta");
					this.OnnumerocuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int")]
		public System.Nullable<int> clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_credito_id", DbType="Int")]
		public System.Nullable<int> servicio_credito_id
		{
			get
			{
				return this._servicio_credito_id;
			}
			set
			{
				if ((this._servicio_credito_id != value))
				{
					if (this._TM_ServicioCredito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onservicio_credito_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_credito_id = value;
					this.SendPropertyChanged("servicio_credito_id");
					this.Onservicio_credito_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_corte", DbType="Real")]
		public System.Nullable<float> balance_corte
		{
			get
			{
				return this._balance_corte;
			}
			set
			{
				if ((this._balance_corte != value))
				{
					this.Onbalance_corteChanging(value);
					this.SendPropertyChanging();
					this._balance_corte = value;
					this.SendPropertyChanged("balance_corte");
					this.Onbalance_corteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_sobregiro", DbType="Real")]
		public System.Nullable<float> balance_sobregiro
		{
			get
			{
				return this._balance_sobregiro;
			}
			set
			{
				if ((this._balance_sobregiro != value))
				{
					this.Onbalance_sobregiroChanging(value);
					this.SendPropertyChanging();
					this._balance_sobregiro = value;
					this.SendPropertyChanged("balance_sobregiro");
					this.Onbalance_sobregiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechacorte", DbType="VarChar(10)")]
		public string fechacorte
		{
			get
			{
				return this._fechacorte;
			}
			set
			{
				if ((this._fechacorte != value))
				{
					this.OnfechacorteChanging(value);
					this.SendPropertyChanging();
					this._fechacorte = value;
					this.SendPropertyChanged("fechacorte");
					this.OnfechacorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_fecha", DbType="Real")]
		public System.Nullable<float> balance_fecha
		{
			get
			{
				return this._balance_fecha;
			}
			set
			{
				if ((this._balance_fecha != value))
				{
					this.Onbalance_fechaChanging(value);
					this.SendPropertyChanging();
					this._balance_fecha = value;
					this.SendPropertyChanged("balance_fecha");
					this.Onbalance_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corte_total", DbType="VarChar(10)")]
		public string corte_total
		{
			get
			{
				return this._corte_total;
			}
			set
			{
				if ((this._corte_total != value))
				{
					this.Oncorte_totalChanging(value);
					this.SendPropertyChanging();
					this._corte_total = value;
					this.SendPropertyChanged("corte_total");
					this.Oncorte_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaCredito", Storage="_TM_Clientes", ThisKey="clienteid", OtherKey="clienteid", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TD_CuentaCredito.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaCredito.Add(this);
						this._clienteid = value.clienteid;
					}
					else
					{
						this._clienteid = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioCredito_TD_CuentaCredito", Storage="_TM_ServicioCredito", ThisKey="servicio_credito_id", OtherKey="servicio_credito_id", IsForeignKey=true)]
		public TM_ServicioCredito TM_ServicioCredito
		{
			get
			{
				return this._TM_ServicioCredito.Entity;
			}
			set
			{
				TM_ServicioCredito previousValue = this._TM_ServicioCredito.Entity;
				if (((previousValue != value) 
							|| (this._TM_ServicioCredito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_ServicioCredito.Entity = null;
						previousValue.TD_CuentaCredito.Remove(this);
					}
					this._TM_ServicioCredito.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaCredito.Add(this);
						this._servicio_credito_id = value.servicio_credito_id;
					}
					else
					{
						this._servicio_credito_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_ServicioCredito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_CuentaPrestamo")]
	public partial class TD_CuentaPrestamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numerocuenta;
		
		private System.Nullable<int> _clienteid;
		
		private System.Nullable<int> _servicio_prestamo_id;
		
		private string _fecha_desembolso;
		
		private System.Nullable<int> _numero_cuotas;
		
		private string _fecha_cancelacion;
		
		private System.Nullable<float> _tasa_interes;
		
		private System.Nullable<float> _monto_total;
		
		private System.Nullable<float> _cuota_no_seguro;
		
		private System.Nullable<float> _cuota_seguro;
		
		private System.Nullable<float> _limite_extraordinario;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_Prestamos> _TM_Prestamos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumerocuentaChanging(int value);
    partial void OnnumerocuentaChanged();
    partial void OnclienteidChanging(System.Nullable<int> value);
    partial void OnclienteidChanged();
    partial void Onservicio_prestamo_idChanging(System.Nullable<int> value);
    partial void Onservicio_prestamo_idChanged();
    partial void Onfecha_desembolsoChanging(string value);
    partial void Onfecha_desembolsoChanged();
    partial void Onnumero_cuotasChanging(System.Nullable<int> value);
    partial void Onnumero_cuotasChanged();
    partial void Onfecha_cancelacionChanging(string value);
    partial void Onfecha_cancelacionChanged();
    partial void Ontasa_interesChanging(System.Nullable<float> value);
    partial void Ontasa_interesChanged();
    partial void Onmonto_totalChanging(System.Nullable<float> value);
    partial void Onmonto_totalChanged();
    partial void Oncuota_no_seguroChanging(System.Nullable<float> value);
    partial void Oncuota_no_seguroChanged();
    partial void Oncuota_seguroChanging(System.Nullable<float> value);
    partial void Oncuota_seguroChanged();
    partial void Onlimite_extraordinarioChanging(System.Nullable<float> value);
    partial void Onlimite_extraordinarioChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TD_CuentaPrestamo()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			this._TM_Prestamos = default(EntityRef<TM_Prestamos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocuenta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int numerocuenta
		{
			get
			{
				return this._numerocuenta;
			}
			set
			{
				if ((this._numerocuenta != value))
				{
					this.OnnumerocuentaChanging(value);
					this.SendPropertyChanging();
					this._numerocuenta = value;
					this.SendPropertyChanged("numerocuenta");
					this.OnnumerocuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int")]
		public System.Nullable<int> clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_prestamo_id", DbType="Int")]
		public System.Nullable<int> servicio_prestamo_id
		{
			get
			{
				return this._servicio_prestamo_id;
			}
			set
			{
				if ((this._servicio_prestamo_id != value))
				{
					if (this._TM_Prestamos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onservicio_prestamo_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_prestamo_id = value;
					this.SendPropertyChanged("servicio_prestamo_id");
					this.Onservicio_prestamo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_desembolso", DbType="VarChar(10)")]
		public string fecha_desembolso
		{
			get
			{
				return this._fecha_desembolso;
			}
			set
			{
				if ((this._fecha_desembolso != value))
				{
					this.Onfecha_desembolsoChanging(value);
					this.SendPropertyChanging();
					this._fecha_desembolso = value;
					this.SendPropertyChanged("fecha_desembolso");
					this.Onfecha_desembolsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_cuotas", DbType="Int")]
		public System.Nullable<int> numero_cuotas
		{
			get
			{
				return this._numero_cuotas;
			}
			set
			{
				if ((this._numero_cuotas != value))
				{
					this.Onnumero_cuotasChanging(value);
					this.SendPropertyChanging();
					this._numero_cuotas = value;
					this.SendPropertyChanged("numero_cuotas");
					this.Onnumero_cuotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cancelacion", DbType="VarChar(10)")]
		public string fecha_cancelacion
		{
			get
			{
				return this._fecha_cancelacion;
			}
			set
			{
				if ((this._fecha_cancelacion != value))
				{
					this.Onfecha_cancelacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_cancelacion = value;
					this.SendPropertyChanged("fecha_cancelacion");
					this.Onfecha_cancelacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_interes", DbType="Real")]
		public System.Nullable<float> tasa_interes
		{
			get
			{
				return this._tasa_interes;
			}
			set
			{
				if ((this._tasa_interes != value))
				{
					this.Ontasa_interesChanging(value);
					this.SendPropertyChanging();
					this._tasa_interes = value;
					this.SendPropertyChanged("tasa_interes");
					this.Ontasa_interesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_total", DbType="Real")]
		public System.Nullable<float> monto_total
		{
			get
			{
				return this._monto_total;
			}
			set
			{
				if ((this._monto_total != value))
				{
					this.Onmonto_totalChanging(value);
					this.SendPropertyChanging();
					this._monto_total = value;
					this.SendPropertyChanged("monto_total");
					this.Onmonto_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuota_no_seguro", DbType="Real")]
		public System.Nullable<float> cuota_no_seguro
		{
			get
			{
				return this._cuota_no_seguro;
			}
			set
			{
				if ((this._cuota_no_seguro != value))
				{
					this.Oncuota_no_seguroChanging(value);
					this.SendPropertyChanging();
					this._cuota_no_seguro = value;
					this.SendPropertyChanged("cuota_no_seguro");
					this.Oncuota_no_seguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuota_seguro", DbType="Real")]
		public System.Nullable<float> cuota_seguro
		{
			get
			{
				return this._cuota_seguro;
			}
			set
			{
				if ((this._cuota_seguro != value))
				{
					this.Oncuota_seguroChanging(value);
					this.SendPropertyChanging();
					this._cuota_seguro = value;
					this.SendPropertyChanged("cuota_seguro");
					this.Oncuota_seguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limite_extraordinario", DbType="Real")]
		public System.Nullable<float> limite_extraordinario
		{
			get
			{
				return this._limite_extraordinario;
			}
			set
			{
				if ((this._limite_extraordinario != value))
				{
					this.Onlimite_extraordinarioChanging(value);
					this.SendPropertyChanging();
					this._limite_extraordinario = value;
					this.SendPropertyChanged("limite_extraordinario");
					this.Onlimite_extraordinarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaPrestamo", Storage="_TM_Clientes", ThisKey="clienteid", OtherKey="clienteid", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TD_CuentaPrestamo.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaPrestamo.Add(this);
						this._clienteid = value.clienteid;
					}
					else
					{
						this._clienteid = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Prestamos_TD_CuentaPrestamo", Storage="_TM_Prestamos", ThisKey="servicio_prestamo_id", OtherKey="servicio_prestamo_id", IsForeignKey=true)]
		public TM_Prestamos TM_Prestamos
		{
			get
			{
				return this._TM_Prestamos.Entity;
			}
			set
			{
				TM_Prestamos previousValue = this._TM_Prestamos.Entity;
				if (((previousValue != value) 
							|| (this._TM_Prestamos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Prestamos.Entity = null;
						previousValue.TD_CuentaPrestamo.Remove(this);
					}
					this._TM_Prestamos.Entity = value;
					if ((value != null))
					{
						value.TD_CuentaPrestamo.Add(this);
						this._servicio_prestamo_id = value.servicio_prestamo_id;
					}
					else
					{
						this._servicio_prestamo_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Prestamos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_Transacciones")]
	public partial class TD_Transacciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _compraid;
		
		private System.Nullable<int> _clienteid;
		
		private string _numerocuenta;
		
		private System.Nullable<float> _monto;
		
		private string _fecha;
		
		private string _comercio;
		
		private System.Nullable<float> _impuesto;
		
		private System.Nullable<bool> _estatus;
		
		private System.Nullable<int> _codigo_referencia;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncompraidChanging(int value);
    partial void OncompraidChanged();
    partial void OnclienteidChanging(System.Nullable<int> value);
    partial void OnclienteidChanged();
    partial void OnnumerocuentaChanging(string value);
    partial void OnnumerocuentaChanged();
    partial void OnmontoChanging(System.Nullable<float> value);
    partial void OnmontoChanged();
    partial void OnfechaChanging(string value);
    partial void OnfechaChanged();
    partial void OncomercioChanging(string value);
    partial void OncomercioChanged();
    partial void OnimpuestoChanging(System.Nullable<float> value);
    partial void OnimpuestoChanged();
    partial void OnestatusChanging(System.Nullable<bool> value);
    partial void OnestatusChanged();
    partial void Oncodigo_referenciaChanging(System.Nullable<int> value);
    partial void Oncodigo_referenciaChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TD_Transacciones()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compraid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int compraid
		{
			get
			{
				return this._compraid;
			}
			set
			{
				if ((this._compraid != value))
				{
					this.OncompraidChanging(value);
					this.SendPropertyChanging();
					this._compraid = value;
					this.SendPropertyChanged("compraid");
					this.OncompraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int")]
		public System.Nullable<int> clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocuenta", DbType="VarChar(40)")]
		public string numerocuenta
		{
			get
			{
				return this._numerocuenta;
			}
			set
			{
				if ((this._numerocuenta != value))
				{
					this.OnnumerocuentaChanging(value);
					this.SendPropertyChanging();
					this._numerocuenta = value;
					this.SendPropertyChanged("numerocuenta");
					this.OnnumerocuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Real")]
		public System.Nullable<float> monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="VarChar(10)")]
		public string fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comercio", DbType="VarChar(40)")]
		public string comercio
		{
			get
			{
				return this._comercio;
			}
			set
			{
				if ((this._comercio != value))
				{
					this.OncomercioChanging(value);
					this.SendPropertyChanging();
					this._comercio = value;
					this.SendPropertyChanged("comercio");
					this.OncomercioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impuesto", DbType="Real")]
		public System.Nullable<float> impuesto
		{
			get
			{
				return this._impuesto;
			}
			set
			{
				if ((this._impuesto != value))
				{
					this.OnimpuestoChanging(value);
					this.SendPropertyChanging();
					this._impuesto = value;
					this.SendPropertyChanged("impuesto");
					this.OnimpuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estatus", DbType="Bit")]
		public System.Nullable<bool> estatus
		{
			get
			{
				return this._estatus;
			}
			set
			{
				if ((this._estatus != value))
				{
					this.OnestatusChanging(value);
					this.SendPropertyChanging();
					this._estatus = value;
					this.SendPropertyChanged("estatus");
					this.OnestatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_referencia", DbType="Int")]
		public System.Nullable<int> codigo_referencia
		{
			get
			{
				return this._codigo_referencia;
			}
			set
			{
				if ((this._codigo_referencia != value))
				{
					this.Oncodigo_referenciaChanging(value);
					this.SendPropertyChanging();
					this._codigo_referencia = value;
					this.SendPropertyChanged("codigo_referencia");
					this.Oncodigo_referenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_Transacciones", Storage="_TM_Clientes", ThisKey="clienteid", OtherKey="clienteid", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TD_Transacciones.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TD_Transacciones.Add(this);
						this._clienteid = value.clienteid;
					}
					else
					{
						this._clienteid = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Clientes")]
	public partial class TM_Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _clienteid;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<int> _cedula;
		
		private System.Nullable<float> _ingresos;
		
		private string _direccion;
		
		private System.Nullable<int> _numero;
		
		private System.Nullable<int> _telefono;
		
		private System.Nullable<int> _puntaje;
		
		private string _username;
		
		private string _clave;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntitySet<TD_CuentaAhorros> _TD_CuentaAhorros;
		
		private EntitySet<TD_CuentaCorriente> _TD_CuentaCorriente;
		
		private EntitySet<TD_CuentaCredito> _TD_CuentaCredito;
		
		private EntitySet<TD_CuentaPrestamo> _TD_CuentaPrestamo;
		
		private EntitySet<TD_Transacciones> _TD_Transacciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclienteidChanging(int value);
    partial void OnclienteidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OncedulaChanging(System.Nullable<int> value);
    partial void OncedulaChanged();
    partial void OningresosChanging(System.Nullable<float> value);
    partial void OningresosChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnnumeroChanging(System.Nullable<int> value);
    partial void OnnumeroChanged();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    partial void OnpuntajeChanging(System.Nullable<int> value);
    partial void OnpuntajeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TM_Clientes()
		{
			this._TD_CuentaAhorros = new EntitySet<TD_CuentaAhorros>(new Action<TD_CuentaAhorros>(this.attach_TD_CuentaAhorros), new Action<TD_CuentaAhorros>(this.detach_TD_CuentaAhorros));
			this._TD_CuentaCorriente = new EntitySet<TD_CuentaCorriente>(new Action<TD_CuentaCorriente>(this.attach_TD_CuentaCorriente), new Action<TD_CuentaCorriente>(this.detach_TD_CuentaCorriente));
			this._TD_CuentaCredito = new EntitySet<TD_CuentaCredito>(new Action<TD_CuentaCredito>(this.attach_TD_CuentaCredito), new Action<TD_CuentaCredito>(this.detach_TD_CuentaCredito));
			this._TD_CuentaPrestamo = new EntitySet<TD_CuentaPrestamo>(new Action<TD_CuentaPrestamo>(this.attach_TD_CuentaPrestamo), new Action<TD_CuentaPrestamo>(this.detach_TD_CuentaPrestamo));
			this._TD_Transacciones = new EntitySet<TD_Transacciones>(new Action<TD_Transacciones>(this.attach_TD_Transacciones), new Action<TD_Transacciones>(this.detach_TD_Transacciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clienteid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int clienteid
		{
			get
			{
				return this._clienteid;
			}
			set
			{
				if ((this._clienteid != value))
				{
					this.OnclienteidChanging(value);
					this.SendPropertyChanging();
					this._clienteid = value;
					this.SendPropertyChanged("clienteid");
					this.OnclienteidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(20)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int")]
		public System.Nullable<int> cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingresos", DbType="Real")]
		public System.Nullable<float> ingresos
		{
			get
			{
				return this._ingresos;
			}
			set
			{
				if ((this._ingresos != value))
				{
					this.OningresosChanging(value);
					this.SendPropertyChanging();
					this._ingresos = value;
					this.SendPropertyChanged("ingresos");
					this.OningresosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(40)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int")]
		public System.Nullable<int> numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntaje", DbType="Int")]
		public System.Nullable<int> puntaje
		{
			get
			{
				return this._puntaje;
			}
			set
			{
				if ((this._puntaje != value))
				{
					this.OnpuntajeChanging(value);
					this.SendPropertyChanging();
					this._puntaje = value;
					this.SendPropertyChanged("puntaje");
					this.OnpuntajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(40)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(40)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaAhorros", Storage="_TD_CuentaAhorros", ThisKey="clienteid", OtherKey="clienteid")]
		public EntitySet<TD_CuentaAhorros> TD_CuentaAhorros
		{
			get
			{
				return this._TD_CuentaAhorros;
			}
			set
			{
				this._TD_CuentaAhorros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaCorriente", Storage="_TD_CuentaCorriente", ThisKey="clienteid", OtherKey="clienteid")]
		public EntitySet<TD_CuentaCorriente> TD_CuentaCorriente
		{
			get
			{
				return this._TD_CuentaCorriente;
			}
			set
			{
				this._TD_CuentaCorriente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaCredito", Storage="_TD_CuentaCredito", ThisKey="clienteid", OtherKey="clienteid")]
		public EntitySet<TD_CuentaCredito> TD_CuentaCredito
		{
			get
			{
				return this._TD_CuentaCredito;
			}
			set
			{
				this._TD_CuentaCredito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_CuentaPrestamo", Storage="_TD_CuentaPrestamo", ThisKey="clienteid", OtherKey="clienteid")]
		public EntitySet<TD_CuentaPrestamo> TD_CuentaPrestamo
		{
			get
			{
				return this._TD_CuentaPrestamo;
			}
			set
			{
				this._TD_CuentaPrestamo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TD_Transacciones", Storage="_TD_Transacciones", ThisKey="clienteid", OtherKey="clienteid")]
		public EntitySet<TD_Transacciones> TD_Transacciones
		{
			get
			{
				return this._TD_Transacciones;
			}
			set
			{
				this._TD_Transacciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_CuentaAhorros(TD_CuentaAhorros entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TD_CuentaAhorros(TD_CuentaAhorros entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
		
		private void attach_TD_CuentaCorriente(TD_CuentaCorriente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TD_CuentaCorriente(TD_CuentaCorriente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
		
		private void attach_TD_CuentaCredito(TD_CuentaCredito entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TD_CuentaCredito(TD_CuentaCredito entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
		
		private void attach_TD_CuentaPrestamo(TD_CuentaPrestamo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TD_CuentaPrestamo(TD_CuentaPrestamo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
		
		private void attach_TD_Transacciones(TD_Transacciones entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TD_Transacciones(TD_Transacciones entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Prestamos")]
	public partial class TM_Prestamos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicio_prestamo_id;
		
		private string _nombre;
		
		private string _tipo;
		
		private System.Nullable<int> _ingresos_minimos;
		
		private System.Nullable<int> _comision_mora;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntitySet<TD_CuentaPrestamo> _TD_CuentaPrestamo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onservicio_prestamo_idChanging(int value);
    partial void Onservicio_prestamo_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void Oningresos_minimosChanging(System.Nullable<int> value);
    partial void Oningresos_minimosChanged();
    partial void Oncomision_moraChanging(System.Nullable<int> value);
    partial void Oncomision_moraChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TM_Prestamos()
		{
			this._TD_CuentaPrestamo = new EntitySet<TD_CuentaPrestamo>(new Action<TD_CuentaPrestamo>(this.attach_TD_CuentaPrestamo), new Action<TD_CuentaPrestamo>(this.detach_TD_CuentaPrestamo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_prestamo_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int servicio_prestamo_id
		{
			get
			{
				return this._servicio_prestamo_id;
			}
			set
			{
				if ((this._servicio_prestamo_id != value))
				{
					this.Onservicio_prestamo_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_prestamo_id = value;
					this.SendPropertyChanged("servicio_prestamo_id");
					this.Onservicio_prestamo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(20)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingresos_minimos", DbType="Int")]
		public System.Nullable<int> ingresos_minimos
		{
			get
			{
				return this._ingresos_minimos;
			}
			set
			{
				if ((this._ingresos_minimos != value))
				{
					this.Oningresos_minimosChanging(value);
					this.SendPropertyChanging();
					this._ingresos_minimos = value;
					this.SendPropertyChanged("ingresos_minimos");
					this.Oningresos_minimosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comision_mora", DbType="Int")]
		public System.Nullable<int> comision_mora
		{
			get
			{
				return this._comision_mora;
			}
			set
			{
				if ((this._comision_mora != value))
				{
					this.Oncomision_moraChanging(value);
					this.SendPropertyChanging();
					this._comision_mora = value;
					this.SendPropertyChanged("comision_mora");
					this.Oncomision_moraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Prestamos_TD_CuentaPrestamo", Storage="_TD_CuentaPrestamo", ThisKey="servicio_prestamo_id", OtherKey="servicio_prestamo_id")]
		public EntitySet<TD_CuentaPrestamo> TD_CuentaPrestamo
		{
			get
			{
				return this._TD_CuentaPrestamo;
			}
			set
			{
				this._TD_CuentaPrestamo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_CuentaPrestamo(TD_CuentaPrestamo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Prestamos = this;
		}
		
		private void detach_TD_CuentaPrestamo(TD_CuentaPrestamo entity)
		{
			this.SendPropertyChanging();
			entity.TM_Prestamos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_ServicioAhorros")]
	public partial class TM_ServicioAhorros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicio_ahorros_id;
		
		private string _nombre;
		
		private System.Nullable<int> _deposito_apertura;
		
		private System.Nullable<int> _balance_minimo;
		
		private System.Nullable<int> _minimo_transferencias;
		
		private System.Nullable<int> _cargo_mensual;
		
		private System.Nullable<float> _tasa_interes;
		
		private System.Nullable<int> _retiro_plazo;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntitySet<TD_CuentaAhorros> _TD_CuentaAhorros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onservicio_ahorros_idChanging(int value);
    partial void Onservicio_ahorros_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ondeposito_aperturaChanging(System.Nullable<int> value);
    partial void Ondeposito_aperturaChanged();
    partial void Onbalance_minimoChanging(System.Nullable<int> value);
    partial void Onbalance_minimoChanged();
    partial void Onminimo_transferenciasChanging(System.Nullable<int> value);
    partial void Onminimo_transferenciasChanged();
    partial void Oncargo_mensualChanging(System.Nullable<int> value);
    partial void Oncargo_mensualChanged();
    partial void Ontasa_interesChanging(System.Nullable<float> value);
    partial void Ontasa_interesChanged();
    partial void Onretiro_plazoChanging(System.Nullable<int> value);
    partial void Onretiro_plazoChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TM_ServicioAhorros()
		{
			this._TD_CuentaAhorros = new EntitySet<TD_CuentaAhorros>(new Action<TD_CuentaAhorros>(this.attach_TD_CuentaAhorros), new Action<TD_CuentaAhorros>(this.detach_TD_CuentaAhorros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_ahorros_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int servicio_ahorros_id
		{
			get
			{
				return this._servicio_ahorros_id;
			}
			set
			{
				if ((this._servicio_ahorros_id != value))
				{
					this.Onservicio_ahorros_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_ahorros_id = value;
					this.SendPropertyChanged("servicio_ahorros_id");
					this.Onservicio_ahorros_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deposito_apertura", DbType="Int")]
		public System.Nullable<int> deposito_apertura
		{
			get
			{
				return this._deposito_apertura;
			}
			set
			{
				if ((this._deposito_apertura != value))
				{
					this.Ondeposito_aperturaChanging(value);
					this.SendPropertyChanging();
					this._deposito_apertura = value;
					this.SendPropertyChanged("deposito_apertura");
					this.Ondeposito_aperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_minimo", DbType="Int")]
		public System.Nullable<int> balance_minimo
		{
			get
			{
				return this._balance_minimo;
			}
			set
			{
				if ((this._balance_minimo != value))
				{
					this.Onbalance_minimoChanging(value);
					this.SendPropertyChanging();
					this._balance_minimo = value;
					this.SendPropertyChanged("balance_minimo");
					this.Onbalance_minimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimo_transferencias", DbType="Int")]
		public System.Nullable<int> minimo_transferencias
		{
			get
			{
				return this._minimo_transferencias;
			}
			set
			{
				if ((this._minimo_transferencias != value))
				{
					this.Onminimo_transferenciasChanging(value);
					this.SendPropertyChanging();
					this._minimo_transferencias = value;
					this.SendPropertyChanged("minimo_transferencias");
					this.Onminimo_transferenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_mensual", DbType="Int")]
		public System.Nullable<int> cargo_mensual
		{
			get
			{
				return this._cargo_mensual;
			}
			set
			{
				if ((this._cargo_mensual != value))
				{
					this.Oncargo_mensualChanging(value);
					this.SendPropertyChanging();
					this._cargo_mensual = value;
					this.SendPropertyChanged("cargo_mensual");
					this.Oncargo_mensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_interes", DbType="Real")]
		public System.Nullable<float> tasa_interes
		{
			get
			{
				return this._tasa_interes;
			}
			set
			{
				if ((this._tasa_interes != value))
				{
					this.Ontasa_interesChanging(value);
					this.SendPropertyChanging();
					this._tasa_interes = value;
					this.SendPropertyChanged("tasa_interes");
					this.Ontasa_interesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_retiro_plazo", DbType="Int")]
		public System.Nullable<int> retiro_plazo
		{
			get
			{
				return this._retiro_plazo;
			}
			set
			{
				if ((this._retiro_plazo != value))
				{
					this.Onretiro_plazoChanging(value);
					this.SendPropertyChanging();
					this._retiro_plazo = value;
					this.SendPropertyChanged("retiro_plazo");
					this.Onretiro_plazoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioAhorros_TD_CuentaAhorros", Storage="_TD_CuentaAhorros", ThisKey="servicio_ahorros_id", OtherKey="servicio_ahorros_id")]
		public EntitySet<TD_CuentaAhorros> TD_CuentaAhorros
		{
			get
			{
				return this._TD_CuentaAhorros;
			}
			set
			{
				this._TD_CuentaAhorros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_CuentaAhorros(TD_CuentaAhorros entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioAhorros = this;
		}
		
		private void detach_TD_CuentaAhorros(TD_CuentaAhorros entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioAhorros = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_ServicioCorriente")]
	public partial class TM_ServicioCorriente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicio_corriente_id;
		
		private string _nombre;
		
		private System.Nullable<int> _deposito_apertura;
		
		private System.Nullable<int> _balance_minimo;
		
		private System.Nullable<int> _minimo_transferencias;
		
		private System.Nullable<int> _cargo_mensual;
		
		private System.Nullable<int> _cargo_bajo_balance;
		
		private System.Nullable<int> _cheques_gratis;
		
		private System.Nullable<int> _cheques_adicionales;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntitySet<TD_CuentaCorriente> _TD_CuentaCorriente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onservicio_corriente_idChanging(int value);
    partial void Onservicio_corriente_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ondeposito_aperturaChanging(System.Nullable<int> value);
    partial void Ondeposito_aperturaChanged();
    partial void Onbalance_minimoChanging(System.Nullable<int> value);
    partial void Onbalance_minimoChanged();
    partial void Onminimo_transferenciasChanging(System.Nullable<int> value);
    partial void Onminimo_transferenciasChanged();
    partial void Oncargo_mensualChanging(System.Nullable<int> value);
    partial void Oncargo_mensualChanged();
    partial void Oncargo_bajo_balanceChanging(System.Nullable<int> value);
    partial void Oncargo_bajo_balanceChanged();
    partial void Oncheques_gratisChanging(System.Nullable<int> value);
    partial void Oncheques_gratisChanged();
    partial void Oncheques_adicionalesChanging(System.Nullable<int> value);
    partial void Oncheques_adicionalesChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TM_ServicioCorriente()
		{
			this._TD_CuentaCorriente = new EntitySet<TD_CuentaCorriente>(new Action<TD_CuentaCorriente>(this.attach_TD_CuentaCorriente), new Action<TD_CuentaCorriente>(this.detach_TD_CuentaCorriente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_corriente_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int servicio_corriente_id
		{
			get
			{
				return this._servicio_corriente_id;
			}
			set
			{
				if ((this._servicio_corriente_id != value))
				{
					this.Onservicio_corriente_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_corriente_id = value;
					this.SendPropertyChanged("servicio_corriente_id");
					this.Onservicio_corriente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deposito_apertura", DbType="Int")]
		public System.Nullable<int> deposito_apertura
		{
			get
			{
				return this._deposito_apertura;
			}
			set
			{
				if ((this._deposito_apertura != value))
				{
					this.Ondeposito_aperturaChanging(value);
					this.SendPropertyChanging();
					this._deposito_apertura = value;
					this.SendPropertyChanged("deposito_apertura");
					this.Ondeposito_aperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_minimo", DbType="Int")]
		public System.Nullable<int> balance_minimo
		{
			get
			{
				return this._balance_minimo;
			}
			set
			{
				if ((this._balance_minimo != value))
				{
					this.Onbalance_minimoChanging(value);
					this.SendPropertyChanging();
					this._balance_minimo = value;
					this.SendPropertyChanged("balance_minimo");
					this.Onbalance_minimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimo_transferencias", DbType="Int")]
		public System.Nullable<int> minimo_transferencias
		{
			get
			{
				return this._minimo_transferencias;
			}
			set
			{
				if ((this._minimo_transferencias != value))
				{
					this.Onminimo_transferenciasChanging(value);
					this.SendPropertyChanging();
					this._minimo_transferencias = value;
					this.SendPropertyChanged("minimo_transferencias");
					this.Onminimo_transferenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_mensual", DbType="Int")]
		public System.Nullable<int> cargo_mensual
		{
			get
			{
				return this._cargo_mensual;
			}
			set
			{
				if ((this._cargo_mensual != value))
				{
					this.Oncargo_mensualChanging(value);
					this.SendPropertyChanging();
					this._cargo_mensual = value;
					this.SendPropertyChanged("cargo_mensual");
					this.Oncargo_mensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_bajo_balance", DbType="Int")]
		public System.Nullable<int> cargo_bajo_balance
		{
			get
			{
				return this._cargo_bajo_balance;
			}
			set
			{
				if ((this._cargo_bajo_balance != value))
				{
					this.Oncargo_bajo_balanceChanging(value);
					this.SendPropertyChanging();
					this._cargo_bajo_balance = value;
					this.SendPropertyChanged("cargo_bajo_balance");
					this.Oncargo_bajo_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cheques_gratis", DbType="Int")]
		public System.Nullable<int> cheques_gratis
		{
			get
			{
				return this._cheques_gratis;
			}
			set
			{
				if ((this._cheques_gratis != value))
				{
					this.Oncheques_gratisChanging(value);
					this.SendPropertyChanging();
					this._cheques_gratis = value;
					this.SendPropertyChanged("cheques_gratis");
					this.Oncheques_gratisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cheques_adicionales", DbType="Int")]
		public System.Nullable<int> cheques_adicionales
		{
			get
			{
				return this._cheques_adicionales;
			}
			set
			{
				if ((this._cheques_adicionales != value))
				{
					this.Oncheques_adicionalesChanging(value);
					this.SendPropertyChanging();
					this._cheques_adicionales = value;
					this.SendPropertyChanged("cheques_adicionales");
					this.Oncheques_adicionalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioCorriente_TD_CuentaCorriente", Storage="_TD_CuentaCorriente", ThisKey="servicio_corriente_id", OtherKey="servicio_corriente_id")]
		public EntitySet<TD_CuentaCorriente> TD_CuentaCorriente
		{
			get
			{
				return this._TD_CuentaCorriente;
			}
			set
			{
				this._TD_CuentaCorriente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_CuentaCorriente(TD_CuentaCorriente entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioCorriente = this;
		}
		
		private void detach_TD_CuentaCorriente(TD_CuentaCorriente entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioCorriente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_ServicioCredito")]
	public partial class TM_ServicioCredito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _servicio_credito_id;
		
		private string _nombre;
		
		private System.Nullable<int> _cargo_anual;
		
		private System.Nullable<float> _tasa_interes;
		
		private System.Nullable<int> _avance_efectivo;
		
		private System.Nullable<int> _sobregiro;
		
		private System.Nullable<int> _cargo_perdida;
		
		private System.Nullable<bool> _FlagActivo;
		
		private EntitySet<TD_CuentaCredito> _TD_CuentaCredito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onservicio_credito_idChanging(int value);
    partial void Onservicio_credito_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Oncargo_anualChanging(System.Nullable<int> value);
    partial void Oncargo_anualChanged();
    partial void Ontasa_interesChanging(System.Nullable<float> value);
    partial void Ontasa_interesChanged();
    partial void Onavance_efectivoChanging(System.Nullable<int> value);
    partial void Onavance_efectivoChanged();
    partial void OnsobregiroChanging(System.Nullable<int> value);
    partial void OnsobregiroChanged();
    partial void Oncargo_perdidaChanging(System.Nullable<int> value);
    partial void Oncargo_perdidaChanged();
    partial void OnFlagActivoChanging(System.Nullable<bool> value);
    partial void OnFlagActivoChanged();
    #endregion
		
		public TM_ServicioCredito()
		{
			this._TD_CuentaCredito = new EntitySet<TD_CuentaCredito>(new Action<TD_CuentaCredito>(this.attach_TD_CuentaCredito), new Action<TD_CuentaCredito>(this.detach_TD_CuentaCredito));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicio_credito_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int servicio_credito_id
		{
			get
			{
				return this._servicio_credito_id;
			}
			set
			{
				if ((this._servicio_credito_id != value))
				{
					this.Onservicio_credito_idChanging(value);
					this.SendPropertyChanging();
					this._servicio_credito_id = value;
					this.SendPropertyChanged("servicio_credito_id");
					this.Onservicio_credito_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_anual", DbType="Int")]
		public System.Nullable<int> cargo_anual
		{
			get
			{
				return this._cargo_anual;
			}
			set
			{
				if ((this._cargo_anual != value))
				{
					this.Oncargo_anualChanging(value);
					this.SendPropertyChanging();
					this._cargo_anual = value;
					this.SendPropertyChanged("cargo_anual");
					this.Oncargo_anualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_interes", DbType="Real")]
		public System.Nullable<float> tasa_interes
		{
			get
			{
				return this._tasa_interes;
			}
			set
			{
				if ((this._tasa_interes != value))
				{
					this.Ontasa_interesChanging(value);
					this.SendPropertyChanging();
					this._tasa_interes = value;
					this.SendPropertyChanged("tasa_interes");
					this.Ontasa_interesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avance_efectivo", DbType="Int")]
		public System.Nullable<int> avance_efectivo
		{
			get
			{
				return this._avance_efectivo;
			}
			set
			{
				if ((this._avance_efectivo != value))
				{
					this.Onavance_efectivoChanging(value);
					this.SendPropertyChanging();
					this._avance_efectivo = value;
					this.SendPropertyChanged("avance_efectivo");
					this.Onavance_efectivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sobregiro", DbType="Int")]
		public System.Nullable<int> sobregiro
		{
			get
			{
				return this._sobregiro;
			}
			set
			{
				if ((this._sobregiro != value))
				{
					this.OnsobregiroChanging(value);
					this.SendPropertyChanging();
					this._sobregiro = value;
					this.SendPropertyChanged("sobregiro");
					this.OnsobregiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_perdida", DbType="Int")]
		public System.Nullable<int> cargo_perdida
		{
			get
			{
				return this._cargo_perdida;
			}
			set
			{
				if ((this._cargo_perdida != value))
				{
					this.Oncargo_perdidaChanging(value);
					this.SendPropertyChanging();
					this._cargo_perdida = value;
					this.SendPropertyChanged("cargo_perdida");
					this.Oncargo_perdidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagActivo", DbType="Bit")]
		public System.Nullable<bool> FlagActivo
		{
			get
			{
				return this._FlagActivo;
			}
			set
			{
				if ((this._FlagActivo != value))
				{
					this.OnFlagActivoChanging(value);
					this.SendPropertyChanging();
					this._FlagActivo = value;
					this.SendPropertyChanged("FlagActivo");
					this.OnFlagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_ServicioCredito_TD_CuentaCredito", Storage="_TD_CuentaCredito", ThisKey="servicio_credito_id", OtherKey="servicio_credito_id")]
		public EntitySet<TD_CuentaCredito> TD_CuentaCredito
		{
			get
			{
				return this._TD_CuentaCredito;
			}
			set
			{
				this._TD_CuentaCredito.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_CuentaCredito(TD_CuentaCredito entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioCredito = this;
		}
		
		private void detach_TD_CuentaCredito(TD_CuentaCredito entity)
		{
			this.SendPropertyChanging();
			entity.TM_ServicioCredito = null;
		}
	}
}
#pragma warning restore 1591
