<?xml version="1.0" encoding="utf-8"?><Database Name="DbGolden" Class="Db_GoldDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-MELI-😊;Initial Catalog=DbGolden;Integrated Security=True;Encrypt=False" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="DbGoldenConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TM_ServicioCredito" Member="TM_ServicioCreditos">
    <Type Name="TM_ServicioCredito">
      <Column Name="servicio_credito_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cargo_anual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="avance_efectivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobregiro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_perdida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioCredito_TD_CuentaCredito" Member="TD_CuentaCreditos" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TD_CuentaCredito" />
      <Association Name="TM_ServicioCredito_TD_CuentaCredito1" Member="TD_CuentaCredito1" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TD_CuentaCredito1" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaAhorros" Member="TD_CuentaAhorros">
    <Type Name="TD_CuentaAhorros">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_ahorros_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaAhorros" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_ServicioAhorros_TD_CuentaAhorros" Member="TM_ServicioAhorros" Storage="_TM_ServicioAhorro" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TM_ServicioAhorros" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaAhorros" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioAhorros1_TD_CuentaAhorros" Member="TM_ServicioAhorros1" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TM_ServicioAhorros1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaCorriente" Member="TD_CuentaCorrientes">
    <Type Name="TD_CuentaCorriente">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_corriente_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="balance_sobregiro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaCorriente" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_ServicioCorriente_TD_CuentaCorriente" Member="TM_ServicioCorriente" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TM_ServicioCorriente" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaCorriente" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioCorriente1_TD_CuentaCorriente" Member="TM_ServicioCorriente1" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TM_ServicioCorriente1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaCredito" Member="TD_CuentaCreditos">
    <Type Name="TD_CuentaCredito">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_credito_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_corte" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="balance_sobregiro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="fechacorte" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="balance_fecha" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="corte_total" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioCredito_TD_CuentaCredito" Member="TM_ServicioCredito" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TM_ServicioCredito" IsForeignKey="true" />
      <Association Name="TM_Clientes_TD_CuentaCredito" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaCredito" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioCredito1_TD_CuentaCredito" Member="TM_ServicioCredito1" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TM_ServicioCredito1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaPrestamo" Member="TD_CuentaPrestamos">
    <Type Name="TD_CuentaPrestamo">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_prestamo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_desembolso" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="numero_cuotas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_cancelacion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="monto_total" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="cuota_no_seguro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="cuota_seguro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="limite_extraordinario" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaPrestamo" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_Prestamos_TD_CuentaPrestamo" Member="TM_Prestamos" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TM_Prestamos" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaPrestamo" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_Prestamos1_TD_CuentaPrestamo" Member="TM_Prestamos1" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TM_Prestamos1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_Login" Member="TD_Logins">
    <Type Name="TD_Login">
      <Column Name="loginId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="url_login" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="createBy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="modifyBy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cancelBy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecCreate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecModify" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecCancel" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_Login" Member="TM_Clientes" ThisKey="clienteId" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_Transacciones" Member="TD_Transacciones">
    <Type Name="TD_Transacciones">
      <Column Name="compraid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numerocuenta" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="monto" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="fecha" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="comercio" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="impuesto" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="codigo_referencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_Transacciones" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_Transacciones" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Clientes" Member="TM_Clientes">
    <Type Name="TM_Clientes">
      <Column Name="clienteid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cedula" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ingresos" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="numero" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="puntaje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="clave" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaAhorros" Member="TD_CuentaAhorros" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaAhorros" />
      <Association Name="TM_Clientes_TD_CuentaCorriente" Member="TD_CuentaCorrientes" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCorriente" />
      <Association Name="TM_Clientes_TD_CuentaCredito" Member="TD_CuentaCreditos" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCredito" />
      <Association Name="TM_Clientes_TD_CuentaPrestamo" Member="TD_CuentaPrestamos" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaPrestamo" />
      <Association Name="TM_Clientes_TD_Login" Member="TD_Logins" ThisKey="clienteid" OtherKey="clienteId" Type="TD_Login" />
      <Association Name="TM_Clientes_TD_Transacciones" Member="TD_Transacciones" ThisKey="clienteid" OtherKey="clienteid" Type="TD_Transacciones" />
      <Association Name="TM_Clientes_TD_CuentaAhorros1" Member="TD_CuentaAhorros1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaAhorros1" />
      <Association Name="TM_Clientes_TD_CuentaCorriente1" Member="TD_CuentaCorriente1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCorriente1" />
      <Association Name="TM_Clientes_TD_CuentaCredito1" Member="TD_CuentaCredito1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCredito1" />
      <Association Name="TM_Clientes_TD_CuentaPrestamo1" Member="TD_CuentaPrestamo1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaPrestamo1" />
      <Association Name="TM_Clientes_TD_Transacciones1" Member="TD_Transacciones1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_Transacciones1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Prestamos" Member="TM_Prestamos">
    <Type Name="TM_Prestamos">
      <Column Name="servicio_prestamo_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ingresos_minimos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comision_mora" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Prestamos_TD_CuentaPrestamo" Member="TD_CuentaPrestamos" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TD_CuentaPrestamo" />
      <Association Name="TM_Prestamos_TD_CuentaPrestamo1" Member="TD_CuentaPrestamo1" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TD_CuentaPrestamo1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_ServicioAhorros" Member="TM_ServicioAhorros">
    <Type Name="TM_ServicioAhorros">
      <Column Name="servicio_ahorros_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposito_apertura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_minimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="minimo_transferencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_mensual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="retiro_plazo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioAhorros_TD_CuentaAhorros" Member="TD_CuentaAhorros" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TD_CuentaAhorros" />
      <Association Name="TM_ServicioAhorros_TD_CuentaAhorros1" Member="TD_CuentaAhorros1" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TD_CuentaAhorros1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_ServicioCorriente" Member="TM_ServicioCorrientes">
    <Type Name="TM_ServicioCorriente">
      <Column Name="servicio_corriente_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposito_apertura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_minimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="minimo_transferencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_mensual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_bajo_balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cheques_gratis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cheques_adicionales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioCorriente_TD_CuentaCorriente" Member="TD_CuentaCorrientes" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TD_CuentaCorriente" />
      <Association Name="TM_ServicioCorriente_TD_CuentaCorriente1" Member="TD_CuentaCorriente1" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TD_CuentaCorriente1" />
    </Type>
  </Table>
  <Table Name="dbo.VW_Usuarios" Member="VW_Usuarios">
    <Type Name="VW_Usuario">
      <Column Name="CodigoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="EstatusUsuario" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PerfilUsuario" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="EstatusLogin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Usuario" Member="TM_Usuario">
    <Type Name="TM_Usuario">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PasswordUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreatBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CancelBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FechaCreate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecModify" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecCancel" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Usuario_TD_Login1" Member="TD_Login1" ThisKey="idUser" OtherKey="idUser" Type="TD_Login1" />
      <Association Name="TM_Usuario_TD_RolesxUsuario" Member="TD_RolesxUsuario" ThisKey="idUser" OtherKey="idUser" Type="TD_RolesxUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaAhorros" Member="TD_CuentaAhorros1">
    <Type Name="TD_CuentaAhorros1">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_ahorros_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaAhorros1" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_ServicioAhorros_TD_CuentaAhorros1" Member="TM_ServicioAhorros" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TM_ServicioAhorros" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaAhorros1" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioAhorros1_TD_CuentaAhorros1" Member="TM_ServicioAhorros1" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TM_ServicioAhorros1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaCorriente" Member="TD_CuentaCorriente1">
    <Type Name="TD_CuentaCorriente1">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_corriente_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="balance_sobregiro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaCorriente1" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_ServicioCorriente_TD_CuentaCorriente1" Member="TM_ServicioCorriente" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TM_ServicioCorriente" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaCorriente1" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioCorriente1_TD_CuentaCorriente1" Member="TM_ServicioCorriente1" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TM_ServicioCorriente1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaCredito" Member="TD_CuentaCredito1">
    <Type Name="TD_CuentaCredito1">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_credito_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_corte" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="balance_sobregiro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="fechacorte" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="balance_fecha" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="corte_total" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaCredito1" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_ServicioCredito_TD_CuentaCredito1" Member="TM_ServicioCredito" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TM_ServicioCredito" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaCredito1" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_ServicioCredito1_TD_CuentaCredito1" Member="TM_ServicioCredito1" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TM_ServicioCredito1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_CuentaPrestamo" Member="TD_CuentaPrestamo1">
    <Type Name="TD_CuentaPrestamo1">
      <Column Name="numerocuenta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="servicio_prestamo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_desembolso" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="numero_cuotas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_cancelacion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="monto_total" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="cuota_no_seguro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="cuota_seguro" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="limite_extraordinario" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_CuentaPrestamo1" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_Prestamos_TD_CuentaPrestamo1" Member="TM_Prestamos" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TM_Prestamos" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_CuentaPrestamo1" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
      <Association Name="TM_Prestamos1_TD_CuentaPrestamo1" Member="TM_Prestamos1" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TM_Prestamos1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_Login" Member="TD_Login1">
    <Type Name="TD_Login1">
      <Column Name="idLogin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="url_login" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CancelBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FechaCreate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecModify" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecCancel" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Usuario_TD_Login1" Member="TM_Usuario" ThisKey="idUser" OtherKey="idUser" Type="TM_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_RolesxUsuario" Member="TD_RolesxUsuario">
    <Type Name="TD_RolesxUsuario">
      <Column Name="idRolesXUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CancelBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FechaCreate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecModify" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecCancel" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Usuario_TD_RolesxUsuario" Member="TM_Usuario" ThisKey="idUser" OtherKey="idUser" Type="TM_Usuario" IsForeignKey="true" />
      <Association Name="TM_Roles_TD_RolesxUsuario" Member="TM_Roles" ThisKey="idRoles" OtherKey="idRoles" Type="TM_Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TD_Transacciones" Member="TD_Transacciones1">
    <Type Name="TD_Transacciones1">
      <Column Name="compraid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clienteid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numerocuenta" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="monto" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="fecha" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="comercio" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="impuesto" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="codigo_referencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes_TD_Transacciones1" Member="TM_Clientes" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes" IsForeignKey="true" />
      <Association Name="TM_Clientes1_TD_Transacciones1" Member="TM_Clientes1" ThisKey="clienteid" OtherKey="clienteid" Type="TM_Clientes1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Clientes" Member="TM_Clientes1">
    <Type Name="TM_Clientes1">
      <Column Name="clienteid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ingresos" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="numero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="puntaje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="clave" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Clientes1_TD_CuentaAhorros" Member="TD_CuentaAhorros" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaAhorros" />
      <Association Name="TM_Clientes1_TD_CuentaAhorros1" Member="TD_CuentaAhorros1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaAhorros1" />
      <Association Name="TM_Clientes1_TD_CuentaCorriente" Member="TD_CuentaCorriente" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCorriente" />
      <Association Name="TM_Clientes1_TD_CuentaCorriente1" Member="TD_CuentaCorriente1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCorriente1" />
      <Association Name="TM_Clientes1_TD_CuentaCredito" Member="TD_CuentaCredito" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCredito" />
      <Association Name="TM_Clientes1_TD_CuentaCredito1" Member="TD_CuentaCredito1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaCredito1" />
      <Association Name="TM_Clientes1_TD_CuentaPrestamo" Member="TD_CuentaPrestamo" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaPrestamo" />
      <Association Name="TM_Clientes1_TD_CuentaPrestamo1" Member="TD_CuentaPrestamo1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_CuentaPrestamo1" />
      <Association Name="TM_Clientes1_TD_Transacciones" Member="TD_Transacciones" ThisKey="clienteid" OtherKey="clienteid" Type="TD_Transacciones" />
      <Association Name="TM_Clientes1_TD_Transacciones1" Member="TD_Transacciones1" ThisKey="clienteid" OtherKey="clienteid" Type="TD_Transacciones1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Prestamos" Member="TM_Prestamos1">
    <Type Name="TM_Prestamos1">
      <Column Name="servicio_prestamo_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ingresos_minimos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comision_mora" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Prestamos1_TD_CuentaPrestamo" Member="TD_CuentaPrestamo" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TD_CuentaPrestamo" />
      <Association Name="TM_Prestamos1_TD_CuentaPrestamo1" Member="TD_CuentaPrestamo1" ThisKey="servicio_prestamo_id" OtherKey="servicio_prestamo_id" Type="TD_CuentaPrestamo1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_Roles" Member="TM_Roles">
    <Type Name="TM_Roles">
      <Column Name="idRoles" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CancelBy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="FechaCreate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecModify" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FecCancel" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_Roles_TD_RolesxUsuario" Member="TD_RolesxUsuario" ThisKey="idRoles" OtherKey="idRoles" Type="TD_RolesxUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.TM_ServicioAhorros" Member="TM_ServicioAhorros1">
    <Type Name="TM_ServicioAhorros1">
      <Column Name="servicio_ahorros_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposito_apertura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_minimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="minimo_transferencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_mensual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="retiro_plazo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioAhorros1_TD_CuentaAhorros" Member="TD_CuentaAhorros" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TD_CuentaAhorros" />
      <Association Name="TM_ServicioAhorros1_TD_CuentaAhorros1" Member="TD_CuentaAhorros1" ThisKey="servicio_ahorros_id" OtherKey="servicio_ahorros_id" Type="TD_CuentaAhorros1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_ServicioCorriente" Member="TM_ServicioCorriente1">
    <Type Name="TM_ServicioCorriente1">
      <Column Name="servicio_corriente_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deposito_apertura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="balance_minimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="minimo_transferencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_mensual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_bajo_balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cheques_gratis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cheques_adicionales" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioCorriente1_TD_CuentaCorriente" Member="TD_CuentaCorriente" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TD_CuentaCorriente" />
      <Association Name="TM_ServicioCorriente1_TD_CuentaCorriente1" Member="TD_CuentaCorriente1" ThisKey="servicio_corriente_id" OtherKey="servicio_corriente_id" Type="TD_CuentaCorriente1" />
    </Type>
  </Table>
  <Table Name="dbo.TM_ServicioCredito" Member="TM_ServicioCredito1">
    <Type Name="TM_ServicioCredito1">
      <Column Name="servicio_credito_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cargo_anual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tasa_interes" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="avance_efectivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobregiro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cargo_perdida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlagActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TM_ServicioCredito1_TD_CuentaCredito" Member="TD_CuentaCredito" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TD_CuentaCredito" />
      <Association Name="TM_ServicioCredito1_TD_CuentaCredito1" Member="TD_CuentaCredito1" ThisKey="servicio_credito_id" OtherKey="servicio_credito_id" Type="TD_CuentaCredito1" />
    </Type>
  </Table>
</Database>